### PR TITLE
Add docker install documentation

### LINKED ISSUE #1: Document Ubuntu 20.04 docker installation

### PR DESCRIPTION
**Pull request by thatnerdjosh**
Resolves #1 
Closes #1
fixes calteknet/documentation#1

### CODE REVIEW

**Comment by thatnerdjosh** [comment]
@kmw @adamdroberts @iuri could I please get reviews on this, and/or suggestions to alter the format, etc

**Review by adamdroberts — APPROVED** [review]
Looks good

**Comment by thatnerdjosh** [comment]
@calteknet/developers I am working on changing this to use the official docker repositories instead of the Ubuntu maintained `docker.io`. Once this is done I'll ping again, please review this in a timely manner once it's done so I could merge it. It's been lingering a while

Thanks

**Comment by thatnerdjosh** [comment]
@calteknet/developers the changes have been made, please review! Thanks 👍 

EDIT: Was testing project automation, so events here get a bit loud

**Comment by zanssa** [comment]
LGTM

**Review by zanssa — APPROVED** [review]

**Review by zanssa — APPROVED** [review]

**Review by zanssa — APPROVED** [review]
Approved

**Review by zanssa — APPROVED** [review]

**Review by zanssa — CHANGES_REQUESTED** [review]
This is for testing!

**Review by zanssa — APPROVED** [review]

**Comment by zanssa** [comment]
resolve #1

**Comment by zanssa** [comment]
Resolved #1
Closed #1
fixed #1

**Pull request merged**
